### ISSUE TITLE
User Story: Navbar

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#1]
*As a* user, *I can* find and access the navigation bar on every page *so that* I can easily navigate to the different sections of the website.

## Acceptance Criteria
- The Navbar should  be visible on every page
- The Navbar should show different links depending on user roles.
- The Navbar layout should be responsive

## Tasks
- [x] - Create the navbar basic structure
- [x] - Add basic routings
- [x] - Add menu for mobile view
- [x] - Implement different routings depending on user roles.
