### ISSUE TITLE
User Story: Delete Car ad

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#12]
*As a*  user, *I can* delete the car ad *so that* I no longer are showing it to other visitors.

## Acceptance Criteria
- Show the link to delete the ad
- Route back to homepage

## Tasks
- [x] - Create link to delete ad
- [x] - Create delete form
- [x] - Route user back to the homepage
- [x] - Check for user ownership
