### ISSUE TITLE
User Story: Top sellers panel

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#13]
*As a*  user, *I can* find a column that shows the top sellers *so that* I can easily check those first

## Acceptance Criteria
- Show a sidepanel that displays the most popular sellers
- Links that goes to each seller
- Button to follow/unfollow each seller

## Tasks
- [x] - Implement functionality for popularity based on follower count
- [x] - Create a sidepanel that shows the most popular sellers
- [x] - Create links in the sidepanel to each seller
- [x] - Create links in the sidepanel to follow/unfollow each seller
