### ISSUE TITLE
User Story: Profile page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#14]
*As a*  user, *I can* click on a profile *so that* I can find more information about the seller.

## Acceptance Criteria
- Link to profile page
- Information about the profile is easy to find
-

## Tasks
- [x] - Create profile page
- [x] - Create link to profile page
- [x] - Add information fields to profile page
