### ISSUE TITLE
User Story: Sign in

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#3]
*As a*  user, *I can* login to my account *so that* I can use the sites features and access my profile.

## Acceptance Criteria
- Users can find the link to login in the navbar
- Users can login using the login form.
- Users are redirected to main page after login.

## Tasks
- [x] - Create sign in link
- [x] - Create sign in form
- [x] - Create a redirect so that successful sign in redirects to main page
