### ISSUE TITLE
User Story: Create car ad page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#6]
*As a*  user, *I can* create an ad for my car *so that* others can view my ad and make inquiries to buy my car.

## Acceptance Criteria
- Users can find the "sell car" button in the navbar
- Users can access the form to create a car ad.
- Error handling implemented in the form.

## Tasks
- [x] - Create link in the navbar that navigate user to the form.
- [x] - Create form page
- [x] - Create error handling 
- [x] - Save the form to the database.
