### ISSUE TITLE
User Story: Car ad details page

### ISSUE THREAD

**Issue by ErikHgm** [ErikHgm/carss-react-frontend#7]
*As a*  user, *I can* click on a car *so that* I can view more details about the car.

## Acceptance Criteria
- View information about the car on a separate page
- View information about the seller of the car
- Save the ad to my car list for future viewing

## Tasks
- [x] - Create the page for single car ad view
- [x] - Create a car ad component
- [x] - Create the save car component
